---
- name: Configuring Dell switch
  hosts: dell
  vars:
    ansible_collections_path: ~/.ansible/collections/ansible_collection
  tasks:
    - name: Merge provided configuration with device configuration
      dellemc.enterprise_sonic.sonic_interfaces:
        config:
          - name: Ethernet 1/1/10:1
            description: Configured by AAP2
        state: merged
