---
- name: Configuring Dell switch
  hosts: dell
  tasks:
    - name: Configure interfaces
      sonic_interfaces:
        config:
          - name: Ethernet 1/1/10:1
            description: Configured by AAP2
        state: merged
