---
- name: Configuring Dell switch
  hosts: dell
  collections:
    - dellemc.enterprise_sonic
  tasks:
   - name: "Configure description for interface in native name"
     sonic_config:
       commands:
         - description Configured by AAP2
       parents:
         - interface Ethernet 1/1/10:1
     vars:
        ansible_command_timeout: 180
