---
- name: Execute Shell Command
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get the directory structure
      find:
        paths: "/usr"
        register: directory_structure
    - name: Display directory structure
      debug:
        var: directory_structure
