---
- name: Provision OpenShift Cluster and Install Python
  hosts: localhost
  gather_facts: false
  become: yes
  become_method: su
  
  tasks:
    - name: Install Python
      dnf:
        name: python3
        state: present

    - name: Install Python PIP
      dnf:
        name: python3-pip
        state: present
