---
- name: Provision HCP cluster
  hosts: localhost
  

  tasks:
    - name: Create temporary directory with write access for playbook user
      file:
        path: /tmp/hcp_install
        state: directory
        mode: 0755  # Allows user to read, write, execute, and group/others can only read and execute

    - name: Download HCP archive to temporary directory
      uri:
        url: https://hcp-cli-download-multicluster-engine.apps.mgm2.tmetse.bos2.lab/linux/amd64/hcp.tar.gz
        dest: /tmp/hcp_install/hcp.tar.gz
        mode: 0644
        validate_certs: no 

    - name: Unpack HCP archive using unarchive module
      ansible.builtin.unarchive:
        # Set src to the downloaded archive path
        src: /tmp/hcp_install/hcp.tar.gz
        # Set dest to the directory where you want to unpack (contents will be placed here)
        dest: /tmp/hcp_install 
    
    - name: Make HCP binary executable
      file:
        path: /tmp/hcp_install/hcp
        mode: +x
        owner: 
        group: 
        dest: /tmp/ssh-key
        mode: 0644  # Optional, set file permissions

    - name: Create file secret with content
      copy:
        content: '{"auths":{"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYmFhZWQwZDE5MjRlNDNmNmE4NzQyYWE0MTY3Y2MwZDc6REJYRElGUTJTWjlKU0RUUzZRVlhDWVkyVzEzSEVWQ1lSNk5INFVTWVQxU0pENEI4TlFIODVDVVBGQUFKMzczSA==","email":"saahmed@redhat.com"}}}'
        dest: /tmp/secret.json
        mode: 0644  # Optional, set file permissions
        
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
        MEM: 16Gi
        CPU: 8
        WORKER_COUNT: 1
        ETCD_STORAGE: ocs-storagecluster-ceph-rbd
        OCP_RELEASE: 4.14.11-x86_64
        PULL_ET_FILE: /tmp/secret.json
        
    #- name: Print environment variable hy
     # debug:
      #    msg: "Secret key content: {{ PULL_SECRET }}"
    - name: Create KubeVirt cluster
      command: /tmp/hcp_install/hcp create cluster kubevirt \
               --name "{{CLUSTER_NAME}}" \
               --node-pool-replicas=2 \
               --memory "{{MEM}}" \
               --cores "{{CPU}}" \
               --pull-secret "{{ PULL_ET_FILE }}" \
               --release-image=quay.io/openshift-release-dev/ocp-release:4.14.11-x86_64 \
               --etcd-storage-class= ocs-storagecluster-ceph-rbd
      
  #- name: Verify HCP installation (using full path)
     # command: /tmp/hcp_install/hcp --version
      #register: hcp_version
    # Optional task to verify installation

     # Optional task to display the HCP version 
