---
- name: Provision HCP cluster
  hosts: localhost
  

  tasks:
    - name: Get Pull Secret from openshift-config namespace
      k8s_info:
        kind: Secret
        namespace: openshift-config
        name: pull-secret
      register: pull_secret_var
    - name: write pull-secret to file
      copy:
        content: "{{ pull_secret_var }}"
        dest: /pull-file


