---
- name: Install HCP binary on Ansible controller
  hosts: localhost

  tasks:
    - name: Download HCP archive
      uri:
        url: https://hcp-cli-download-multicluster-engine.apps.mgm2.tmetse.bos2.lab/linux/arm64/hcp.tar.gz
        dest: /tmp/hcp.tar.gz
        mode: 0644

    - name: Unpack HCP archive
      archive:
        path: /tmp/hcp.tar.gz
        extract: yes
        owner: root
        group: root

    - name: Make HCP binary executable
      file:
        path: /tmp/hcp
        mode: +x
        owner: root
        group: root

    - name: Copy HCP binary to system path
      copy:
        src: /tmp/hcp
        dest: /usr/local/bin/hcp
        owner: root
        group: root
        mode: 0755

    # Optional task to verify installation
    - name: Verify HCP installation
      command: hcp --version
      register: hcp_version
    
      when: not hcp_version.rc == 0  # Only run verification if hcp is not already installed
