---
- name: Provision HCP cluster
  hosts: localhost
  

  tasks:
    - name: Create temporary directory with write access for playbook user
      file:
        path: /tmp/hcp_install
        state: directory
        mode: 0755  # Allows user to read, write, execute, and group/others can only read and execute

    - name: Download HCP archive to temporary directory
      uri:
        url: https://hcp-cli-download-multicluster-engine.apps.mgm2.tmetse.bos2.lab/linux/amd64/hcp.tar.gz
        dest: /tmp/hcp_install/hcp.tar.gz
        mode: 0644
        validate_certs: no 

    - name: Unpack HCP archive using unarchive module
      ansible.builtin.unarchive:
        # Set src to the downloaded archive path
        src: /tmp/hcp_install/hcp.tar.gz
        # Set dest to the directory where you want to unpack (contents will be placed here)
        dest: /tmp/hcp_install 
    
    - name: Make HCP binary executable
      file:
        path: /tmp/hcp_install/hcp
        mode: +x
        owner: 
        group: 
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
        MEM: 16Gi
        CPU: 8
        WORKER_COUNT: 1
        ETCD_STORAGE: ocs-storagecluster-ceph-rbd
        OCP_RELEASE: 4.14.11-x86_64
        PULL_SECRET: "{{ lookup('env', 'PULL_SECRET') }}"
    - name: Print environment variable hy
      debug:
          msg: "Secret key content: {{ PULL_SECRET }}"
    - name: Create KubeVirt cluster
      command: /tmp/hcp_install/hcp create cluster kubevirt \
               --name "{{CLUSTER_NAME}}" \
               --node-pool-replicas=1 \
               --memory "{{MEM}}" \
               --cores "{{CPU}}" \
               --release-image=quay.io/openshift-ease:4.14.11-x86_64 \
               --pull-secret= {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYmFhZWQwZDE5MjRlNDNmNmE4NzQyYWE0MTY3Y2MwZDc6REJYRElGUTJTWjlKU0RUUzZRVlhDWVkyVzEzSEVWQ1lSNk5INFVTWVQxU0pENEI4TlFIODVDVVBGQUFKMzczSA==","email":"saahmed@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYmFhZWQwZDE5MjRlNDNmNmE4NzQyYWE0MTY3Y2MwZDc6REJYRElGUTJTWjlKU0RUUzZRVlhDWVkyVzEzSEVWQ1lSNk5INFVTWVQxU0pENEI4TlFIODVDVVBGQUFKMzczSA==","email":"saahmed@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTdmOGE1OTE1LTQ0NWQtNGU5OC05NmExLTU3MTBlZTc5MzdkZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhOelkyTVdWaFlqWXlZVGcwTWpaaVlqWTJZMlkzT1RZM1pqRXpZelE1WmlKOS5od2RYelJvajlWVnA2SmlMRUM0eVpkZ0Y1ZVQ5UVprSnZSZENYb21RVzNiS1l3S0xvMWlTeUhSZEZjNzV5ODJjbVN5Z3dtOV9Ob3B2UThaS2NHZWJkNjk4cUlNM3hiS09nSTF3SjYxdjVXNUdOLTl5YUpMWjQyRXNoWmJrVmZEU0swaG1WX3R3UHhrMHBWdk5MdF9iZlFORTByQ2M2WXRDeXJuLVB6N0pXMVUtbDlsOVpKbUFfR1pIN0JLYXQ3Ny1pUHJTNll5NzFzSlM3VERTdHJEdFhvaEdvSFF1SU1fOXhYQWpvWGZwaXZxMi1XU3E3T3NENng4c1hadl9sRTdkaHJpUGMycURtOVY4VWx3cEtjTExocE9zTnFaMDY0TWRIblVHZ1laSnE3RVNIU1NvaWdCZ3l2dkpSVnZKaG0yUXN3X25zQTJmQTZHWnR0UF9DSjdVSldldkhPWkpkSGMwQ1Z3Wl9ia1FrdnBXSWRTSVlVdVBoM2ZXNXRuZVZOSFhITEp4XzNCbmZ5SGpBWTNuejNaUE9lblhKSEtjVl9QOWZZOVREa3V4QzhOVjYzWUVCSVJMZDhmVnZPeDRhYlVIWTF3SGhxZ2g2ZjJIZjdxRGNfeDdfc0trTmhjUmVXMXZncUtiRnhnaklMcVQyWmVHUmJMQm1tOWJjWF9pUkJXb1ZXdDZFaEdOQ2FUakxfWGk4OUhUSFBRNzZJc2FSeU5fMDNOUXJqYjF5YXRMd1RMcDVlWDYtWFFCV3U5UjBHNVVvYm96MzFXY2Z2d195aVh5OG5qd1M4cjQ5V1VfN3JhMUVseENnOFU2TTNPUllORkppZ3JaalhGQzVvZzBDYUhzd083d3JiZUdxZXdWNFVmT21pSXF1U0pySGxRNzFaVUpWNU8zRjhkVUVRWQ==","email":"saahmed@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTdmOGE1OTE1LTQ0NWQtNGU5OC05NmExLTU3MTBlZTc5MzdkZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXhOelkyTVdWaFlqWXlZVGcwTWpaaVlqWTJZMlkzT1RZM1pqRXpZelE1WmlKOS5od2RYelJvajlWVnA2SmlMRUM0eVpkZ0Y1ZVQ5UVprSnZSZENYb21RVzNiS1l3S0xvMWlTeUhSZEZjNzV5ODJjbVN5Z3dtOV9Ob3B2UThaS2NHZWJkNjk4cUlNM3hiS09nSTF3SjYxdjVXNUdOLTl5YUpMWjQyRXNoWmJrVmZEU0swaG1WX3R3UHhrMHBWdk5MdF9iZlFORTByQ2M2WXRDeXJuLVB6N0pXMVUtbDlsOVpKbUFfR1pIN0JLYXQ3Ny1pUHJTNll5NzFzSlM3VERTdHJEdFhvaEdvSFF1SU1fOXhYQWpvWGZwaXZxMi1XU3E3T3NENng4c1hadl9sRTdkaHJpUGMycURtOVY4VWx3cEtjTExocE9zTnFaMDY0TWRIblVHZ1laSnE3RVNIU1NvaWdCZ3l2dkpSVnZKaG0yUXN3X25zQTJmQTZHWnR0UF9DSjdVSldldkhPWkpkSGMwQ1Z3Wl9ia1FrdnBXSWRTSVlVdVBoM2ZXNXRuZVZOSFhITEp4XzNCbmZ5SGpBWTNuejNaUE9lblhKSEtjVl9QOWZZOVREa3V4QzhOVjYzWUVCSVJMZDhmVnZPeDRhYlVIWTF3SGhxZ2g2ZjJIZjdxRGNfeDdfc0trTmhjUmVXMXZncUtiRnhnaklMcVQyWmVHUmJMQm1tOWJjWF9pUkJXb1ZXdDZFaEdOQ2FUakxfWGk4OUhUSFBRNzZJc2FSeU5fMDNOUXJqYjF5YXRMd1RMcDVlWDYtWFFCV3U5UjBHNVVvYm96MzFXY2Z2d195aVh5OG5qd1M4cjQ5V1VfN3JhMUVseENnOFU2TTNPUllORkppZ3JaalhGQzVvZzBDYUhzd083d3JiZUdxZXdWNFVmT21pSXF1U0pySGxRNzFaVUpWNU8zRjhkVUVRWQ==","email":"saahmed@redhat.com"}}} \
               --etcd-storage-class= ocs-storagecluster-ceph-rbd
      
  #- name: Verify HCP installation (using full path)
     # command: /tmp/hcp_install/hcp --version
      #register: hcp_version
    # Optional task to verify installation

     # Optional task to display the HCP version 
