---
- name: Get IP Address of Host
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display IP Address
      debug:
        msg: "The IP address is {{ ansible_facts['ansible_default_ipv4']['address'] }}"
