---
- name: Get IP Address of Host
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display IP Address
      debug:
        var: ansible_default_ipv4.address
      register: ip_address_result

    - name: Print IP Address
      debug:
        msg: "The IP address is {{ ip_address_result.stdout_lines[0] }}"
