---
- name: Check OpenShift Cluster Connection
  hosts: hcp-hosts
  connection: local
  gather_facts: false
  tasks:
    - name: Get Pods (default namespace)
      command: oc get pods
      register: pods
    - name: Print Pods (optional)
      debug:
        msg: "Pods: {{ pods.stdout }}"
