---
- name: Check OpenShift Cluster Connection
  hosts: localhost
  k8s:
      api_version: v1
      kind: ServerVersion
    register: cluster_version

  - name: Print cluster version
    debug:
      msg: "Kubernetes Cluster Version: {{ cluster_version.apiVersion }} ({{ cluster_version.major }}.{{ cluster_version.minor }})"
