---
- name: Check OpenShift Cluster Connection
  hosts: hcp-hosts
  tasks:
   - name: Get cluster version
     k8s:
       api_version: v1
       kind: ServerVersion
     register: cluster_version

   - name: Print cluster version
     debug:
       msg: "OpenShift Cluster Version: {{ cluster_version.openshift_version }}"
