---
- name: Check OpenShift Cluster Connection
  hosts: localhost
  tasks:
   - name: Get cluster version
     k8s:
       api_version: v1
       kind: ServerVersion
       kubeconfig: /path/to/your/kubec.yml  # Replace with the actual path
     register: cluster_version

   - name: Print cluster version
     debug:
       msg: "OpenShift Cluster Version: {{ cluster_version.openshift_version }}"
