---
- hosts: localhost
  tasks:
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
    - name: Print environment variable hy
      debug:
          msg: "SSH key content: {{ lookup('env', 'PA') }}"
    
    - name: Print filename from PA environment variable
      debug:
          msg: "Filename: {{ lookup('env', 'PA') | basename }}"
      
