---
- hosts: localhost
  tasks:
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
    - name: Print environment variable hy
      debug:
          msg: " key content: {{ lookup('env', 'CLUSTER_NAME') }}"
    - name: Print environment variable hy
      debug:
          msg: "SSH key content: {{ lookup('env', 'PULL_SECRET') }}"
    
