---
- hosts: localhost
  tasks:
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
    - name: Print environment variable hy
      debug:
          msg: "SSH key content: {{ lookup('env', 'PULL_SECRET') }}"
    
    - name: Read pull secret file content
      slurp:
        path: "{{ PULL_SECRET_PATH }}"
      register: pull_secret_content
    - name: Print pull secret content (optional)
      debug:
        msg: "Pull secret content: {{ pull_secret_content.content }}"
        
