---
- hosts: localhost
  tasks:
    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: hcp-test-app
    - name: Print environment variable hy
      debug:
          msg: "SSH key content: {{ lookup('env', 'PA') }}"
    
    - name: List directory contents if PA points to a directory (careful!)
      shell: ls {{ lookup('env', 'PA') }}
      when: PA_IS_SET and  lookup('file', lookup('env', 'PA') ).isdir
