---
- name: Create a file with content
  hosts: localhost  # Replace with your target hosts
  tasks:
    - name: Create file /path/to/your/file.txt with content
      copy:
        content: "{"auths":{"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYmFhZWQwZDE5MjRlNDNmNmE4NzQyYWE0MTY3Y2MwZDc6REJYRElGUTJTWjlKU0RUUzZRVlhDWVkyVzEzSEVWQ1lSNk5INFVTWVQxU0pENEI4TlFIODVDVVBGQUFKMzczSA==","email":"saahmed@redhat.com"}}}"
        dest: /tmp/secret.json
        mode: 0644  # Optional, set file permissions
