---
- name: Create a NS
  hosts: localhost 
  tasks:
   #- name: Print environment variable hy
    # debug:
     #     msg: "K8S_AUTH: {{ lookup('env', 'KUBECONFIG') }}"
  # - name: View kubectl configuration
   #  command: kubectl config view 
    # #command: kubectl config view --kubeconfig "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
     #register: kubectl_config_output
  collections: 
    - community.kubernetes

  - name: View kubectl configuration
    community.kubernetes.k8s_info::
      api_version: v1
      kind: Pod
      namespace: default
    register: pod_list
  - name: Show captured output (optional)
    debug:
      var: pod_list.stdout
