---
- name: Create a NS
  hosts: localhost 
  tasks:
   - name: Print environment variable hy
     debug:
          msg: "K8S_AUTH: {{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
   - name: View kubectl configuration
     command: kubectl config view --kubeconfig "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
    # environment:
     #  K8S_AUTH_KUBECONFIG: "{{ tower.filename.kubeconfig }}"
     register: kubectl_config_output
  
   - name: Show captured output (optional)
     debug:
       var: kubectl_config_output.stdout
