---
- name: Create a NS
  hosts: localhost 
  tasks:
   - name: Print the value of environment variable "MY_VAR"
      debug:
        msg: The value of MY_VAR is: {{ lookup('ansible.builtin.env', 'K8S_AUTH_KUBECONFIG') }}
  # - name: View kubectl configuration
   #  command: kubectl config view
    # environment:
     #  K8S_AUTH_KUBECONFIG: "{{ tower.filename.kubeconfig }}"
     #register: kubectl_config_output
  
 #  - name: Show captured output (optional)
  #   debug:
   #    var: kubectl_config_output.stdout
