---
- name: Create a NS
  hosts: localhost 
  tasks:
   - name: Get kubectl config
      command: kubectl config view
      register: kubectl_config_output
  
   - name: Show captured output (optional)
     debug:
       var: kubectl_config_output.stdout
