---
- name: Create a NS
  hosts: localhost 
  tasks:
   - name: View kubectl configuration
     command: kubectl config view
     environment:
       K8S_AUTH_KUBECONFIG: "{{ tower.filename.kubeconfig }}"
     register: kubectl_config_output
  
   - name: Show captured output (optional)
     debug:
       var: kubectl_config_output.stdout
