---
- name: Create a NS
  hosts: localhost 
  tasks:
   #- name: Print environment variable hy
    # debug:
     #     msg: "K8S_AUTH: {{ lookup('env', 'KUBECONFIG') }}"
  # - name: View kubectl configuration
   #  command: kubectl config view 
    # #command: kubectl config view --kubeconfig "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
     #register: kubectl_config_output


  - name: View kubectl configuration
    kubernetes.core.k8s_cluster_info:
      invalidate_cache: False
    register: api_status
  - name: Show captured output (optional)
    debug:
      var: api_status.stdout
