---
- name: Configuring Dell switch
  hosts: dell
  collections:
    - dellemc.enterprise_sonic
  vars:
      ansible_command_timeout: 120
  tasks:
    - name: Test SONiC single command
      sonic_command:
        commands: 'show interface status'
      register: cmd_op
