---
- name: Listen for events from AlertManager
  hosts: all

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_host_path: ""
  
  rules:
    - name: Debug Hello event
      action:
        echo: "Hello, the playbook is running!"
