---
- name: Listen for events from AlertManager
  hosts: all

  sources:
    - name: listen for timer events
      timer:
        interval: 60 
  
  rules:
    - name: Debug Hello event
      action:
        echo: "Hello, the playbook is running!"
