---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  tasks:
    - name: Debug | Print received alert payload
      debug:
        var: event

  rules:
    - name: EDA-AlertManager-Run playbook to handle alerts
      condition: event.alert.status == "firing"
      action:
        run_job_template:
          name: "Resize PVC"
          organization: Default
          
