---
- name: Install Python
  hosts: all
  become: yes

  tasks:
    - name: Install Python 3.8 (for Red Hat-based systems)
      yum:
        name: python38
        state: present
      when: ansible_os_family == 'RedHat'
